### PR TITLE
Add streaming API

### LINKED ISSUE #4: Parse streaming responses
Some actions (like pulling images, viewing logs, attaching to containers etc.) produce streaming output. We should parse these HTTP streaming responses into individual virtual streams and forward any events on the virtual stream.

Also notice the difference between HTTP/1.0 and HTTP/1.1 requests.

HTTP/1.0 streaming body:
```
echo -en "POST /images/create?fromImage=clue/redis-benchmark HTTP/1.0\r\n\r\n" | nc -U /var/run/docker.sock
HTTP/1.0 200 OK
Content-Type: application/json
Date: Thu, 27 Nov 2014 09:42:15 GMT

{"status":"Pulling repository clue/redis-benchmark"}
{"status":"Pulling image (latest) from clue/redis-benchmark","progressDetail":{},"id":"478a1142ea76"}{"status":"Pulling image (latest) from clue/redis-benchmark, endpoint: https://registry-1.docker.io/v1/","progressDetail":{},"id":"478a1142ea76"}{"status":"Pulling dependent layers","progressDetail":{},"id":"478a1142ea76"}{"status":"Download complete","progressDetail":{},"id":"511136ea3c5a"}{"status":"Download complete","progressDetail":{},"id":"f10807909bc5"}{"status":"Download complete","progressDetail":{},"id":"f6fab3b798be"}{"status":"Download complete","progressDetail":{},"id":"1e6ac0ffed3b"}{"status":"Download complete","progressDetail":{},"id":"62ff5003ac9a"}{"status":"Download complete","progressDetail":{},"id":"c6e4fc6c4a10"}{"status":"Download complete","progressDetail":{},"id":"984fd90de307"}{"status":"Download complete","progressDetail":{},"id":"4784dfba86d0"}{"status":"Download complete","progressDetail":{},"id":"4d4120826ad3"}{"status":"Download complete","progressDetail":{},"id":"b2428b25e452"}{"status":"Download complete","progressDetail":{},"id":"28995deeed39"}{"status":"Download complete","progressDetail":{},"id":"9cd1838bd19c"}{"status":"Download complete","progressDetail":{},"id":"c78781ea905b"}{"status":"Download complete","progressDetail":{},"id":"d7173b5f3fc7"}{"status":"Download complete","progressDetail":{},"id":"6a8a6a35a96b"}{"status":"Download complete","progressDetail":{},"id":"28fdd31ac753"}{"status":"Download complete","progressDetail":{},"id":"3ce54e911389"}{"status":"Download complete","progressDetail":{},"id":"b7261e19024d"}{"status":"Download complete","progressDetail":{},"id":"bb182a1a4f8e"}{"status":"Download complete","progressDetail":{},"id":"cabbf32a5995"}{"status":"Download complete","progressDetail":{},"id":"478a1142ea76"}{"status":"Download complete","progressDetail":{},"id":"478a1142ea76"}{"status":"Status: Image is up to date for clue/redis-benchmark"}
…
```

HTTP/1.1 streaming body uses chunked encoding:
```
$ echo -en "POST /images/create?fromImage=clue/redis-benchmark HTTP/1.1\r\n\r\n" | nc -U /var/run/docker.sock    
HTTP/1.1 200 OK
Content-Type: application/json
Date: Thu, 27 Nov 2014 09:43:27 GMT
Transfer-Encoding: chunked

36
{"status":"Pulling repository clue/redis-benchmark"}

65
{"status":"Pulling image (latest) from clue/redis-benchmark","progressDetail":{},"id":"478a1142ea76"}
91
{"status":"Pulling image (latest) from clue/redis-benchmark, endpoint: https://registry-1.docker.io/v1/","progressDetail":{},"id":"478a1142ea
76"}
4d
{"status":"Pulling dependent layers","progressDetail":{},"id":"478a1142ea76"}
46
{"status":"Download complete","progressDetail":{},"id":"511136ea3c5a"}
46
{"status":"Download complete","progressDetail":{},"id":"f10807909bc5"}
46
{"status":"Download complete","progressDetail":{},"id":"f6fab3b798be"}
46
{"status":"Download complete","progressDetail":{},"id":"1e6ac0ffed3b"}
46
{"status":"Download complete","progressDetail":{},"id":"62ff5003ac9a"}
46
…
```

### PR DESCRIPTION
**Pull request by clue**
Refs #4

### CODE REVIEW

**Comment by adamlc** [comment]
Looks good! I'm going to give it a test now :)

**Comment by clue** [comment]
Thanks for your feedback!

In order to get this in faster, this PR will only address adding a streaming API for existing endpoints, it is not about adding additional endpoints.

This PR lacks some documentation.

The existing endpoints `containerExport()` and `containerCopy()` return streams in the TAR file format and afaict there's no easy way to consume these via React PHP. As such, I've looked into creating a library over at https://github.com/clue/php-tar-react . We won't necessarily have to include this here, but we should provide some documentation. This PR will be postponed for now.

**Comment by clue** [comment]
> I've looked into creating a library over at https://github.com/clue/php-tar-react . We won't necessarily have to include this here, but we should provide some documentation. This PR will be postponed for now.

I've just released an early v0.1.0 of [clue/tar-react](https://github.com/clue/php-tar-react), so I can now continue looking into this PR :)

**Comment by clue** [comment]
Remaining TODOs:

* Streaming API for containerPush endpoint
* Documentation

**Comment by clue** [comment]
I've just added [caret notation](https://github.com/clue/caret-notation) encoding to the copy/export example, so that dumping binary files does not screw up your terminal.

Now getting back to the last missing tests..

**Comment by clue** [comment]
There you go, I've just completed the last TODOs and removed the WIP marker.

Any feedback is very much appreciated! :+1:

**Comment by adamlc** [comment]
Awesome! I'll try and give it a whirl over the next couple of days!

**Comment by clue** [comment]
> Awesome! I'll try and give it a whirl over the next couple of days!

Awesome, let me know if you get to this!

Two remaining issues:

* Remove Promise progress API (see #4 for discussion)
* Reject Promise if progress messages indicate an error (see #21 for background)

**Comment by clue** [comment]
I think this is finally completed :clap: 

This is a non-trivial feature addition, so this can probably use another review :)

**Comment by clue** [comment]
> This is a non-trivial feature addition, so this can probably use another review :)

Either way, let's get this in :shipit:

**Pull request merged**
